packageExtensions:
  "@webpack-contrib/schema-utils@*":
    dependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-docgen-typescript-plugin@*:
    dependencies:
      typescript: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.2.cjs
